version: '3'
services:
  checker:
    container_name: checker
    environment:
      - LANG=en_US.UTF-8
      - TZ=Asia/Shanghai
      - https_proxy=http://pi:10810
    image: fly97/chrome
    volumes:
      - ./:/opt/checker:ro
    command: bash -c "cd /opt/checker;./checker"
    