version: '3'
services:
  checker:
    image: fly97/chrome:arm64
    environment:
      - LANG=en_US.UTF-8
      - TZ=Asia/Shanghai
      - https_proxy=http://nx:10810
    volumes:
      - ./src:/opt/checker:ro
    command: bash -c "cd /opt/checker;./glados-checkin"
    