version: '3'
services:
  checker:
    build: .
    environment:
      - LANG=en_US.UTF-8
      - TZ=Asia/Shanghai
      - https_proxy=http://192.168.31.75:7890
    volumes:
      - ./src:/opt/checker:ro
    entrypoint: bash -c "cd /opt/checker;./glados-checkin"
    