version: '3'
services:
  checker:
    build: .
    environment:
      - LANG=en_US.UTF-8
      - TZ=Asia/Shanghai
    volumes:
      - ./src:/src:ro
    entrypoint: bash -c "strings /lib/x86_64-linux-gnu/libc.so.6 |grep GLIBC_; cd /src; checker"
    